# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a92b12d9d2db0555844997d8be0b0549190dda59e3a8191a79fd6e543fcc88988078bb552824222e57f61acde794f82a436a47236bd0b6c3a9cd73900e7b002

test:
  secret_key_base: aef21bf767884d5bd731be5dd34e706ae8ecb04528a1c22698f10c16273ace6eebb825c8ede24281caac4a5b152f0170457f5c4814f108e7416e8b92ca6aa51f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
